"""user add confirmed

Revision ID: 116d2a8ea29b
Revises: e3926bdd4b64
Create Date: 2016-07-06 19:50:26.140780

"""

# revision identifiers, used by Alembic.
revision = '116d2a8ea29b'
down_revision = 'e3926bdd4b64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
