"""user avatar

Revision ID: 3e705b57c18a
Revises: aceeff0d5c9d
Create Date: 2016-07-17 23:06:38.884988

"""

# revision identifiers, used by Alembic.
revision = '3e705b57c18a'
down_revision = 'aceeff0d5c9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
