"""post

Revision ID: dcf7fbdce9bb
Revises: d4d71276e56a
Create Date: 2016-07-22 00:29:01.808832

"""

# revision identifiers, used by Alembic.
revision = 'dcf7fbdce9bb'
down_revision = 'd4d71276e56a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
